-- Your code here
DROP TABLE customers;
DROP TABLE coffee_orders;

CREATE TABLE customers(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(40) NOT NULL,
  phone NUMERIC(10,0) UNIQUE,
  email VARCHAR(255) UNIQUE,
  points INTEGER DEFAULT 5,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE coffee_orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  is_redeemed BOOLEAN DEFAULT FALSE,
  ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
